# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  bin = "bin"
  cmd = "go build -o bin ."
  include_ext = ["go", "tpl", "tmpl", "html"]
  exclude_dir = ["assets", "tmp", "vendor"]
  delay = 1000
  stop_on_error = false

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
